# List Workflows

GET https://api.github.com/repos/longht021189/bot/actions/workflows
Accept: application/vnd.github+json
X-GitHub-Api-Version: 2022-11-28

HTTP/1.1 200  - OK
server: GitHub.com
date: Fri, 21 Jul 2023 05:21:56 GMT
content-type: application/json; charset=utf-8
cache-control: public, max-age=60, s-maxage=60
vary: Accept, Accept-Encoding, Accept, X-Requested-With
etag: W/"35cc5cbc614c8c9edb493af3fa2185792ec3c9258fe95554061b28feab14509a"
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
content-encoding: gzip
x-ratelimit-limit: 60
x-ratelimit-remaining: 53
x-ratelimit-reset: 1689917737
x-ratelimit-resource: core
x-ratelimit-used: 7
accept-ranges: bytes
content-length: 361
x-github-request-id: 99C7:2149:E4004F:EC4F43:64BA15F4
connection: close
###
# Get Workflows by ID #59229996

GET https://api.github.com/repos/longht021189/bot/actions/workflows/59229996
Accept: application/vnd.github+json
X-GitHub-Api-Version: 2022-11-28

HTTP/1.1 200  - OK
server: GitHub.com
date: Fri, 21 Jul 2023 04:37:40 GMT
content-type: application/json; charset=utf-8
cache-control: public, max-age=60, s-maxage=60
vary: Accept, Accept-Encoding, Accept, X-Requested-With
etag: W/"54d7afa64cbb93ad3e104970658853555e78518716c4f16a08f895d2c0568326"
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
content-encoding: gzip
x-ratelimit-limit: 60
x-ratelimit-remaining: 58
x-ratelimit-reset: 1689917737
x-ratelimit-resource: core
x-ratelimit-used: 2
accept-ranges: bytes
content-length: 261
x-github-request-id: BA9D:11D0:415C09:443CB5:64BA0B94
connection: close
###
PUT https://api.github.com/repos/longht021189/bot/actions/workflows/59229996/disable
Accept: application/vnd.github+json
X-GitHub-Api-Version: 2022-11-28

HTTP/1.1 403  - Forbidden
server: GitHub.com
date: Mon, 05 Jun 2023 03:18:35 GMT
content-type: application/json; charset=utf-8
transfer-encoding: chunked
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
x-ratelimit-limit: 60
x-ratelimit-remaining: 59
x-ratelimit-reset: 1685938715
x-ratelimit-used: 1
x-ratelimit-resource: core
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
content-encoding: gzip
x-github-request-id: D450:1DF7:24E2D25:26C2DD4:647D540A
connection: close
###
PUT https://api.github.com/repos/longht021189/bot/actions/workflows/59229996/enable
Accept: application/vnd.github+json
X-GitHub-Api-Version: 2022-11-28

HTTP/1.1 403  - Forbidden
server: GitHub.com
date: Mon, 05 Jun 2023 03:20:37 GMT
content-type: application/json; charset=utf-8
transfer-encoding: chunked
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
x-ratelimit-limit: 60
x-ratelimit-remaining: 57
x-ratelimit-reset: 1685938715
x-ratelimit-used: 3
x-ratelimit-resource: core
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
content-encoding: gzip
x-github-request-id: D464:239B:704E6A:76EDB4:647D5485
connection: close
###
# Create Access Token Here https://github.com/settings/tokens
# Run Action in `main` Branch

POST https://api.github.com/repos/longht021189/bot/actions/workflows/59229996/dispatches
Accept: application/vnd.github+json
Authorization: Bearer <Token>
X-GitHub-Api-Version: 2022-11-28

{"ref":"main","inputs":{"name":"Mona the Octocat"}}

HTTP/1.1 204  - No Content
server: GitHub.com
date: Fri, 21 Jul 2023 04:48:14 GMT
github-authentication-token-expiration: 2023-08-20 11:46:26 +0700
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
x-ratelimit-limit: 5000
x-ratelimit-remaining: 4997
x-ratelimit-reset: 1689918400
x-ratelimit-used: 3
x-ratelimit-resource: core
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
x-github-request-id: 9E85:20EF:443AC3:4728A3:64BA0E0E
connection: close
###
GET https://api.github.com/repos/longht021189/bot/actions/workflows/59229996/timing
Accept: application/vnd.github+json
X-GitHub-Api-Version: 2022-11-28

HTTP/1.1 404  - Not Found
server: GitHub.com
date: Fri, 21 Jul 2023 04:51:09 GMT
content-type: application/json; charset=utf-8
x-github-media-type: github.v3; format=json
x-github-api-version-selected: 2022-11-28
access-control-expose-headers: ETag, Link, Location, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Used, X-RateLimit-Resource, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval, X-GitHub-Media-Type, X-GitHub-SSO, X-GitHub-Request-Id, Deprecation, Sunset
access-control-allow-origin: *
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: origin-when-cross-origin, strict-origin-when-cross-origin
content-security-policy: default-src 'none'
vary: Accept-Encoding, Accept, X-Requested-With
content-encoding: gzip
x-ratelimit-limit: 60
x-ratelimit-remaining: 56
x-ratelimit-reset: 1689917738
x-ratelimit-resource: core
x-ratelimit-used: 4
content-length: 116
x-github-request-id: 13EC:20EF:449E5E:478FE2:64BA0EBD
connection: close