name: Build-Wallet-Core

on:
  workflow_dispatch:
    inputs:
      note:
        description: 'Note'
        required: false
        type: string

jobs:
  build-wallet-core:
    runs-on: macos-latest
    steps:
      - name: Checkout wallet-core
        uses: actions/checkout@v4
        with:
          repository: 'longht021189/wallet-core'
          ref: 'custom'
          path: 'wallet-core'
      - name: Checkout bot
        uses: actions/checkout@v4
        with:
          path: 'bot'
      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Build wallet-core
        env:
          WALLET_CORE_DIR: ${{ github.workspace }}/wallet-core
          BUILD_DIR: ${{ github.workspace }}/build
          INSTALL_DIR: ${{ github.workspace }}/install
          OUT_DIR: ${{ github.workspace }}/out/wallet-core
        run: bash ${{ github.workspace }}/bot/build/wallet-core/build.sh
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          path: ${{ github.workspace }}/out/wallet-core
          name: wallet-core-osx